// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jlpkhkxnzwehjiemgpvg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpscGtoa3huendlaGppZW1ncHZnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIzNzI0NTYsImV4cCI6MjA2Nzk0ODQ1Nn0.Qk4dV1LWebShqHgqflY3mIuLvzHHzU2yMVyxuawBMRk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});